### ISSUE TITLE
id mit doppelten "

### ISSUE THREAD

**Issue by m-r-h-n** [heimrichhannot/contao-twig-templates-bundle#4]
moin,
erstmal dickes danke für eure erweiterung. 

ich habe testweise einmal mit mod_navigation.html.twig herumgespielt.
dabei fiel mir auf, dass wenn eine id im backend eingegeben wird, diese im frontend mit doppelten anführungszeichen ausgegeben wird. also so: id=""bla""
nachdem ich das template von
`{{ cssID|default }}`
zu
`{{ cssID|default|raw }}`
angepasst habe, wird alles korrekt ausgegeben.

**Comment by koertho** [comment]
@m-r-h-n Sehr gerne! Und danke für die Meldung des Fehlers! Solle in Version 2.1.7 behoben sein.
