### ISSUE TITLE
block_searchable.html.twig - Fehlermeldung bzw. überschreiben

### ISSUE THREAD

**Issue by mj1985** [heimrichhannot/contao-twig-templates-bundle#6]
**Context**
Contao version: 4.12/4.13
Bundle version:  2.4.5
PHP version: 7.4

**Description**
Moin,
ich bekomme im Zusammenhang mit der Nutzung des Contao Catalog Managers bei einem Modul immer die Meldung das die Variable `class` im Template `block_searchable.html.twig` nicht existiert. 
Die Lösung ist denkbar einfach, ein `|default` hinter die Variable und das Problem ist gelöst. Allerdings kann ich das Template nicht überschreiben, egal in welchen Ordner (versucht habe ich es in `/templates`, `/templates/bundles/`, `/contao/templates` ) ich es lege.
Wie kann ich das Template einbinden, damit es überschrieben wird und könnte man das `|default` nicht ggf. in der Erweiterung einbauen?

***Fehlermeldung***
```
Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "class" does not exist." at /home/vagrant/contao/vendor/heimrichhannot/contao-twig-templates-bundle/src/Resources/views/block/block_searchable.html.twig line 1
```

**Comment by koertho** [comment]
Überschreibung sollte funktionieren, wenn es unter /templates/bundles/HeimrichHannotTwigTemplates/block/block_searchable.html.twig abgelegt wird. 

Ansonsten ja, absolut korrekt, ein default gehört dahin.

**Comment by jennrei** [comment]
Ist in der 2.4.6 behoben :)

**Comment by mj1985** [comment]
Überschreiben funktioniert leider nicht. Fehlermeldung ist die gleiche.
![image](https://user-images.githubusercontent.com/5830093/167403041-c6c7ae44-dad5-45f2-8e23-a5401a70418f.png)

Ich hab soweit auch schon in meinen anderen Templates geguckt, ob ich das irgendwo noch extra angeben habe. Ich nutze noch die BS5 Templates.

@jennrei Danke für den schnellen Fix! Wollte gerade einen PR anbieten.

**Comment by koertho** [comment]
Achso, wenn du das BS5-Bundles nutzt, muss der Bundle-Name natürlich angepasst werden.
